// Country code to World Bank region mapping
export const COUNTRY_REGION_MAPPING = {
  // East Asia & Pacific
  'AUS': 'East Asia & Pacific',
  'BRN': 'East Asia & Pacific',
  'CHN': 'East Asia & Pacific',
  'FJI': 'East Asia & Pacific',
  'IDN': 'East Asia & Pacific',
  'JPN': 'East Asia & Pacific',
  'KHM': 'East Asia & Pacific',
  'KOR': 'East Asia & Pacific',
  'LAO': 'East Asia & Pacific',
  'MNG': 'East Asia & Pacific',
  'MYS': 'East Asia & Pacific',
  'NZL': 'East Asia & Pacific',
  'PHL': 'East Asia & Pacific',
  'PNG': 'East Asia & Pacific',
  'SGP': 'East Asia & Pacific',
  'THA': 'East Asia & Pacific',
  'TWN': 'East Asia & Pacific',
  'VNM': 'East Asia & Pacific',
  'HKG': 'East Asia & Pacific',
  'MAC': 'East Asia & Pacific',
  'TON': 'East Asia & Pacific',
  'VUT': 'East Asia & Pacific',
  'WSM': 'East Asia & Pacific',
  'SLB': 'East Asia & Pacific',
  'PLW': 'East Asia & Pacific',
  'NRU': 'East Asia & Pacific',
  'MHL': 'East Asia & Pacific',
  'KIR': 'East Asia & Pacific',
  'FSM': 'East Asia & Pacific',
  'TUV': 'East Asia & Pacific',
  'NCL': 'East Asia & Pacific',
  'PYF': 'East Asia & Pacific',
  'GUM': 'East Asia & Pacific',
  'ASM': 'East Asia & Pacific',
  'COK': 'East Asia & Pacific',
  'NRU': 'East Asia & Pacific',
  'MMR': 'East Asia & Pacific',

  // Europe & Central Asia
  'ALB': 'Europe & Central Asia',
  'ARM': 'Europe & Central Asia',
  'AUT': 'Europe & Central Asia',
  'AZE': 'Europe & Central Asia',
  'BEL': 'Europe & Central Asia',
  'BGR': 'Europe & Central Asia',
  'BIH': 'Europe & Central Asia',
  'BLR': 'Europe & Central Asia',
  'CHE': 'Europe & Central Asia',
  'CYP': 'Europe & Central Asia',
  'CZE': 'Europe & Central Asia',
  'DEU': 'Europe & Central Asia',
  'DNK': 'Europe & Central Asia',
  'ESP': 'Europe & Central Asia',
  'EST': 'Europe & Central Asia',
  'FIN': 'Europe & Central Asia',
  'FRA': 'Europe & Central Asia',
  'GBR': 'Europe & Central Asia',
  'GEO': 'Europe & Central Asia',
  'GRC': 'Europe & Central Asia',
  'HRV': 'Europe & Central Asia',
  'HUN': 'Europe & Central Asia',
  'IRL': 'Europe & Central Asia',
  'ISL': 'Europe & Central Asia',
  'ITA': 'Europe & Central Asia',
  'KAZ': 'Europe & Central Asia',
  'KGZ': 'Europe & Central Asia',
  'LTU': 'Europe & Central Asia',
  'LUX': 'Europe & Central Asia',
  'LVA': 'Europe & Central Asia',
  'MDA': 'Europe & Central Asia',
  'MKD': 'Europe & Central Asia',
  'MLT': 'Europe & Central Asia',
  'MNE': 'Europe & Central Asia',
  'NLD': 'Europe & Central Asia',
  'NOR': 'Europe & Central Asia',
  'POL': 'Europe & Central Asia',
  'PRT': 'Europe & Central Asia',
  'ROU': 'Europe & Central Asia',
  'RUS': 'Europe & Central Asia',
  'SRB': 'Europe & Central Asia',
  'SVK': 'Europe & Central Asia',
  'SVN': 'Europe & Central Asia',
  'SWE': 'Europe & Central Asia',
  'TJK': 'Europe & Central Asia',
  'TKM': 'Europe & Central Asia',
  'TUR': 'Europe & Central Asia',
  'UKR': 'Europe & Central Asia',
  'UZB': 'Europe & Central Asia',
  'XKX': 'Europe & Central Asia', // Kosovo

  // Latin America & Caribbean
  'ARG': 'Latin America & Caribbean',
  'BOL': 'Latin America & Caribbean',
  'BRA': 'Latin America & Caribbean',
  'CHL': 'Latin America & Caribbean',
  'COL': 'Latin America & Caribbean',
  'CRI': 'Latin America & Caribbean',
  'CUB': 'Latin America & Caribbean',
  'DOM': 'Latin America & Caribbean',
  'ECU': 'Latin America & Caribbean',
  'GTM': 'Latin America & Caribbean',
  'HND': 'Latin America & Caribbean',
  'HTI': 'Latin America & Caribbean',
  'JAM': 'Latin America & Caribbean',
  'MEX': 'Latin America & Caribbean',
  'NIC': 'Latin America & Caribbean',
  'PAN': 'Latin America & Caribbean',
  'PER': 'Latin America & Caribbean',
  'PRY': 'Latin America & Caribbean',
  'SLV': 'Latin America & Caribbean',
  'URY': 'Latin America & Caribbean',
  'VEN': 'Latin America & Caribbean',
  'BLZ': 'Latin America & Caribbean',
  'GUY': 'Latin America & Caribbean',
  'SUR': 'Latin America & Caribbean',
  'TTO': 'Latin America & Caribbean',
  'BHS': 'Latin America & Caribbean',
  'BRB': 'Latin America & Caribbean',
  'GRD': 'Latin America & Caribbean',
  'LCA': 'Latin America & Caribbean',
  'VCT': 'Latin America & Caribbean',
  'DMA': 'Latin America & Caribbean',
  'ATG': 'Latin America & Caribbean',
  'KNA': 'Latin America & Caribbean',

  // Middle East & North Africa
  'DZA': 'Middle East & North Africa',
  'BHR': 'Middle East & North Africa',
  'EGY': 'Middle East & North Africa',
  'IRN': 'Middle East & North Africa',
  'IRQ': 'Middle East & North Africa',
  'ISR': 'Middle East & North Africa',
  'JOR': 'Middle East & North Africa',
  'KWT': 'Middle East & North Africa',
  'LBN': 'Middle East & North Africa',
  'LBY': 'Middle East & North Africa',
  'MAR': 'Middle East & North Africa',
  'OMN': 'Middle East & North Africa',
  'PSE': 'Middle East & North Africa',
  'QAT': 'Middle East & North Africa',
  'SAU': 'Middle East & North Africa',
  'SYR': 'Middle East & North Africa',
  'TUN': 'Middle East & North Africa',
  'ARE': 'Middle East & North Africa',
  'YEM': 'Middle East & North Africa',
  'MLT': 'Middle East & North Africa',
  'SDN': 'Middle East & North Africa',

  // North America
  'CAN': 'North America',
  'USA': 'North America',
  'MEX': 'Latin America & Caribbean', // Mexico is classified under Latin America by World Bank

  // South Asia
  'AFG': 'South Asia',
  'BGD': 'South Asia',
  'BTN': 'South Asia',
  'IND': 'South Asia',
  'LKA': 'South Asia',
  'MDV': 'South Asia',
  'NPL': 'South Asia',
  'PAK': 'South Asia',

  // Sub-Saharan Africa
  'AGO': 'Sub-Saharan Africa',
  'BDI': 'Sub-Saharan Africa',
  'BEN': 'Sub-Saharan Africa',
  'BFA': 'Sub-Saharan Africa',
  'BWA': 'Sub-Saharan Africa',
  'CAF': 'Sub-Saharan Africa',
  'CIV': 'Sub-Saharan Africa',
  'CMR': 'Sub-Saharan Africa',
  'COD': 'Sub-Saharan Africa',
  'COG': 'Sub-Saharan Africa',
  'COM': 'Sub-Saharan Africa',
  'CPV': 'Sub-Saharan Africa',
  'DJI': 'Sub-Saharan Africa',
  'ERI': 'Sub-Saharan Africa',
  'ETH': 'Sub-Saharan Africa',
  'GAB': 'Sub-Saharan Africa',
  'GHA': 'Sub-Saharan Africa',
  'GIN': 'Sub-Saharan Africa',
  'GMB': 'Sub-Saharan Africa',
  'GNB': 'Sub-Saharan Africa',
  'GNQ': 'Sub-Saharan Africa',
  'KEN': 'Sub-Saharan Africa',
  'LBR': 'Sub-Saharan Africa',
  'LSO': 'Sub-Saharan Africa',
  'MDG': 'Sub-Saharan Africa',
  'MLI': 'Sub-Saharan Africa',
  'MOZ': 'Sub-Saharan Africa',
  'MRT': 'Sub-Saharan Africa',
  'MUS': 'Sub-Saharan Africa',
  'MWI': 'Sub-Saharan Africa',
  'NAM': 'Sub-Saharan Africa',
  'NER': 'Sub-Saharan Africa',
  'NGA': 'Sub-Saharan Africa',
  'RWA': 'Sub-Saharan Africa',
  'SEN': 'Sub-Saharan Africa',
  'SLE': 'Sub-Saharan Africa',
  'SOM': 'Sub-Saharan Africa',
  'STP': 'Sub-Saharan Africa',
  'SWZ': 'Sub-Saharan Africa',
  'SYC': 'Sub-Saharan Africa',
  'TCD': 'Sub-Saharan Africa',
  'TGO': 'Sub-Saharan Africa',
  'TZA': 'Sub-Saharan Africa',
  'UGA': 'Sub-Saharan Africa',
  'ZAF': 'Sub-Saharan Africa',
  'ZMB': 'Sub-Saharan Africa',
  'ZWE': 'Sub-Saharan Africa'
}

// Function to get region for a country code
export const getRegionForCountry = (countryCode) => {
  return COUNTRY_REGION_MAPPING[countryCode] || 'Unknown Region'
}

// Function to get all countries in a region
export const getCountriesInRegion = (regionName) => {
  return Object.entries(COUNTRY_REGION_MAPPING)
    .filter(([code, region]) => region === regionName)
    .map(([code, region]) => code)
}

// Function to get all available regions
export const getAllRegions = () => {
  return [...new Set(Object.values(COUNTRY_REGION_MAPPING))]
}

// World Bank region definitions with colors from RegionList.jsx
export const WORLD_BANK_REGIONS = [
  {
    name: "East Asia & Pacific",
    description: "Countries spanning from East Asia to Pacific islands",
    emoji: "🌏",
    color: "#ff6b6b",
    lightColor: "#ffe0e0"
  },
  {
    name: "Europe & Central Asia", 
    description: "European nations and Central Asian republics",
    emoji: "🏰",
    color: "#4ecdc4",
    lightColor: "#e0f7f5"
  },
  {
    name: "Latin America & Caribbean",
    description: "South American countries and Caribbean nations", 
    emoji: "🌺",
    color: "#45b7d1",
    lightColor: "#e0f4fd"
  },
  {
    name: "Middle East & North Africa",
    description: "Countries spanning Middle East and North Africa",
    emoji: "🏜️",
    color: "#f9ca24",
    lightColor: "#fef9e0"
  },
  {
    name: "North America",
    description: "United States, Canada, and Mexico",
    emoji: "🍁",
    color: "#6c5ce7",
    lightColor: "#f0edff"
  },
  {
    name: "South Asia",
    description: "Indian subcontinent and surrounding nations",
    emoji: "🕌",
    color: "#fd79a8",
    lightColor: "#fde8f0"
  },
  {
    name: "Sub-Saharan Africa",
    description: "African countries south of the Sahara desert",
    emoji: "🦁",
    color: "#00b894",
    lightColor: "#e0f5f1"
  }
]
